
USE SYSTEM
GO

CREATE PROC SP_REGISTRARROL(
@DESCRIPCION VARCHAR(100),
@ACTIVO BIT,
@MENSAJE VARCHAR(500) OUTPUT,
@RESULTADO INT OUTPUT
)
AS
BEGIN
	SET @RESULTADO = 0
	IF NOT EXISTS (SELECT * FROM ROL WHERE DESCRIPCION = @DESCRIPCION)
	BEGIN
		INSERT INTO ROL(DESCRIPCION,ACTIVO) VALUES
		(@DESCRIPCION,@ACTIVO)

		SET @RESULTADO = SCOPE_IDENTITY()
	END
	ELSE
	 SET @MENSAJE = 'LA ROL YA EXISTE'
END

GO

CREATE PROC SP_EDITARROL(
@IDROL INT,
@DESCRIPCION VARCHAR(100),
@ACTIVO BIT,
@MENSAJE VARCHAR(500) OUTPUT,
@RESULTADO BIT OUTPUT
)
AS
BEGIN
	SET @RESULTADO = 0
	IF NOT EXISTS (SELECT * FROM ROL WHERE DESCRIPCION = @DESCRIPCION AND IDROL != @IDROL)
	BEGIN

		UPDATE TOP (1) ROL SET 
		DESCRIPCION = @DESCRIPCION,
		ACTIVO = @ACTIVO
		WHERE IDROL = @IDROL

		SET @RESULTADO = 1
	END
	ELSE
	 SET @MENSAJE = 'LA ROL YA EXISTE'
END

GO

CREATE PROC SP_ELIMINARROL(
@IDROL INT,
@MENSAJE VARCHAR(500) OUTPUT,
@RESULTADO BIT OUTPUT
)
AS
BEGIN
	SET @RESULTADO = 0
	IF NOT EXISTS (SELECT * FROM USUARIO U
	INNER JOIN ROL R ON R.IDROL = U.IDROL
	WHERE U.IDROL = @IDROL)
	BEGIN
		DELETE TOP (1) FROM ROL WHERE IDROL = @IDROL
		SET @RESULTADO = 1
	END
	ELSE
	 SET @MENSAJE = 'EL ROL SE ENCUENTRA RELACIONADO A UN USUARIO'
END

GO
CREATE PROCEDURE SP_OBTENERROL
AS
BEGIN
SELECT IDROL,DESCRIPCION,ACTIVO FROM ROL
END
GO

---------------Usuarios----------------

CREATE PROCEDURE SP_REGISTRARUSUARIO
    @NOMBRES VARCHAR(100),
    @APELLIDOS VARCHAR(100),
    @CORREO VARCHAR(100),
    @CLAVE VARCHAR(150),  -- USAMOS 150 PARA LA CONTRASEÑA, YA QUE EN LA TABLA ESTÁ COMO VARCHAR(150)
    @ACTIVO BIT,
    @IDROL INT, 
    @MENSAJE VARCHAR(500) OUTPUT,
    @RESULTADO INT OUTPUT
AS
BEGIN
    SET @RESULTADO = 0
    SET @MENSAJE = ''

    -- VERIFICAMOS SI EL CORREO YA EXISTE
    IF NOT EXISTS (SELECT 1 FROM USUARIO WHERE CORREO = @CORREO)
    BEGIN
        -- INSERTAMOS EL NUEVO USUARIO, INCLUYENDO EL IDROL
        INSERT INTO USUARIO (NOMBRES, APELLIDOS, CORREO, CLAVE, ACTIVO, IDROL)
        VALUES (@NOMBRES, @APELLIDOS, @CORREO, @CLAVE, @ACTIVO, @IDROL)

        -- RECUPERAMOS EL ID DEL USUARIO RECIÉN INSERTADO
        SET @RESULTADO = SCOPE_IDENTITY()
    END
    ELSE
    BEGIN
        -- SI YA EXISTE EL CORREO, DEVOLVEMOS UN MENSAJE DE ERROR
        SET @MENSAJE = 'EL CORREO DEL USUARIO YA EXISTE'
    END
END
GO

CREATE PROCEDURE SP_EDITARUSUARIO
    @IDUSUARIO INT,
    @NOMBRES VARCHAR(100),
    @APELLIDOS VARCHAR(100),
    @CORREO VARCHAR(100),
    @ACTIVO BIT,
    @IDROL INT, 
    @MENSAJE VARCHAR(500) OUTPUT,
    @RESULTADO BIT OUTPUT
AS
BEGIN
    SET @RESULTADO = 0
    SET @MENSAJE = ''

    -- VERIFICAMOS SI EL CORREO NO EXISTE PARA OTRO USUARIO
    IF NOT EXISTS (SELECT 1 FROM USUARIO WHERE CORREO = @CORREO AND IDUSUARIO != @IDUSUARIO)
    BEGIN
        -- ACTUALIZAMOS LOS DATOS DEL USUARIO, INCLUYENDO EL CAMPO IDROL
        UPDATE USUARIO
        SET NOMBRES = @NOMBRES,
            APELLIDOS = @APELLIDOS,
            CORREO = @CORREO,
            ACTIVO = @ACTIVO,
            IDROL = @IDROL 
        WHERE IDUSUARIO = @IDUSUARIO

        SET @RESULTADO = 1
    END
    ELSE
    BEGIN
        -- SI EL CORREO YA EXISTE, DEVOLVEMOS UN MENSAJE DE ERROR
        SET @MENSAJE = 'EL CORREO DEL USUARIO YA EXISTE'
    END
END
GO

CREATE PROCEDURE SP_ELIMINARUSUARIO
    @IDUSUARIO INT,
    @RESULTADO BIT OUTPUT
AS
BEGIN
    SET @RESULTADO = 0

    -- VERIFICAMOS QUE EL USUARIO EXISTA
    IF EXISTS (SELECT 1 FROM USUARIO WHERE IDUSUARIO = @IDUSUARIO)
    BEGIN
        DELETE FROM USUARIO WHERE IDUSUARIO = @IDUSUARIO
        SET @RESULTADO = 1
    END
    ELSE
    BEGIN
        -- SI NO EXISTE EL USUARIO, DEVOLVEMOS UN ERROR
        SET @RESULTADO = 0
    END
END
GO
CREATE PROCEDURE SP_OBTENERUSUARIO
AS
BEGIN
SELECT 
    U.IDUSUARIO,
    U.NOMBRES,
    U.APELLIDOS,
    U.CORREO,
	R.IDROL, 
    R.DESCRIPCION,  -- Alias para que coincida con el formato de tu DataTable
    U.ACTIVO
FROM 
    USUARIO U
JOIN 
    ROL R ON U.IDROL = R.IDROL;

END
GO
