USE MASTER
GO
CREATE DATABASE SYSTEM
GO
USE SYSTEM
GO

CREATE TABLE ROL(
IDROL INT PRIMARY KEY IDENTITY,
DESCRIPCION VARCHAR(100),
ACTIVO BIT DEFAULT 1,
FECHAREGISTRO DATETIME DEFAULT GETDATE()
)
GO

CREATE TABLE USUARIO(
IDUSUARIO INT PRIMARY KEY IDENTITY,
NOMBRES VARCHAR(100),
APELLIDOS VARCHAR(100),
CORREO VARCHAR(100),
CLAVE VARCHAR(150),
REESTABLECER BIT DEFAULT 1,
ACTIVO BIT DEFAULT 1,
IDROL INT REFERENCES ROL(IDROL),
FECHAREGISTRO DATETIME DEFAULT GETDATE()
)

GO

